merge selectivity to branch
pingcap/tikv-client-java pull request #106
Opened 2017-09-21 06:16 UTC by birdstorm

2017-09-22 06:50 UTC, zhexuany requested changes

2017-09-22 06:50 UTC, zhexuany commented on src/main/java/com/pingcap/tikv/statistics/Histogram.java
> +    ArrayList<Bucket> tmpBuckets = new ArrayList<>(4096);
Use List instead of ArrayList when declare a type.

2017-09-22 06:50 UTC, zhexuany commented on src/main/java/com/pingcap/tikv/statistics/Histogram.java
> +    ArrayList<Bucket> tmpBuckets = new ArrayList<>(4096);
Additionally, could you make this 4096 finalize?

2017-09-22 06:50 UTC, zhexuany commented on src/main/java/com/pingcap/tikv/statistics/Histogram.java
> +    for(int i = 0; i < 4096; i ++) tmpBuckets.add(new Bucket());
When you decide make 4096 finalize, you can use that variable name here.

2017-09-22 06:50 UTC, zhexuany commented on src/main/java/com/pingcap/tikv/statistics/Histogram.java
> +        e.printStackTrace();
You can create Exception such as `TiHistgoramException`?

2017-09-22 06:50 UTC, zhexuany commented on src/main/java/com/pingcap/tikv/statistics/Histogram.java
>    // mergeBuckets is used to merge every two neighbor buckets.
Here, when you want to use comments, please follow google java style.

2017-09-25 06:54 UTC, birdstorm commented
Incorrect use of Comparables result in test failure.
- [ ] rewriting Histogram logic to merge with #84

2017-11-09 15:12 UTC, zhexuany approved these changes

2017-11-09 15:12 UTC, merged