first commit on refactor on comparables
pingcap/tikv-client-java pull request #131
Opened 2017-11-06 23:09 UTC by zhexuany

2017-11-20 07:16 UTC, birdstorm commented on src/main/java/com/pingcap/tikv/expression/TiConstant.java
> +    return value.getDataType();
I wonder what happens if the value is of `BigDecimal` type, will this be a potential bug here?

2017-11-20 07:16 UTC, birdstorm commented on src/main/java/com/pingcap/tikv/meta/TiSelectRequest.java
> -import com.pingcap.tikv.kvproto.Coprocessor.KeyRange;
why is this import deleted?

2017-11-20 07:20 UTC, zhexuany commented on src/main/java/com/pingcap/tikv/expression/TiConstant.java
> +    return value.getDataType();
Yeah. This what I am trying to prevent.

2017-11-20 07:20 UTC, zhexuany commented on src/main/java/com/pingcap/tikv/expression/TiConstant.java
> +    return value.getDataType();
More stuff come out tonight(CDT)

2017-11-30 18:06 UTC, ilovesoup requested changes

2017-11-30 18:06 UTC, ilovesoup commented on src/test/java/com/pingcap/tikv/predicates/PredicateUtilsTest.java
> +            new TiConstant(1),
what's the purpose to replace static method with new?

2017-11-30 18:06 UTC, ilovesoup commented on src/main/java/com/pingcap/tikv/util/BytesComparable.java
> +    ByteArrayOutputStream bos = new ByteArrayOutputStream();
This looks completely wrong by design.
A comparableBytes means it's comparable in the same way as the order defined in TiDB type system. Once you convert them like this, the original order lost. You might get 1.1 > 2.2 or something like this stuff. This looks not right if they are not bytestring or byte.

2017-11-30 18:26 UTC, ilovesoup commented on src/main/java/com/pingcap/tikv/util/BytesComparable.java
> +    if(getObjectValue() instanceof ByteString) {
Use FastByteComparisons borrowed from Cassandra/Guava. That one is a lot faster.

2017-12-15 09:23 UTC, closed without merging

2017-12-15 09:24 UTC, zhexuany commented
@ilovesoup is working on this. Closing.